### ISSUE TITLE
Add better tests to make sure that parsers are well-behaved

### ISSUE THREAD

**Issue by jsl** [stackbuilders/simple_templates#37]
Parser classes should be consistent about returning Array-like structures. Make sure that we have sufficient tests in the `SimpleTemplates::Parser` class to detect poorly-behaved parser classes, and add tests to the parser classes (e.g., Placeholder, Text) to make sure that they don't return `nil` for things like remaining_tokens.

**Comment by Centeno448** [comment]
Closing since library is being deprecated.
