### ISSUE TITLE
Make parsed result serializable

### ISSUE THREAD

**Issue by jsl** [stackbuilders/simple_templates#43]
Currently, we have separate steps for parsing and interpolation. This should make it easy to save processing time, when multiple rounds of interpolation are needed, by serializing the AST. However, I don't think that the AST can currently be serialized. Implement a `to_json` method so that the parsed result (AST) can be serialized and deserialized.

**Comment by acamino** [comment]
@jsl this request was introduced in #44. I'm closing this issue.
